import {useEffect,useRef} from 'react';import * as echarts from 'echarts';import type {DashboardChartResult,DashboardRunSuccess} from '../../application';
export function AnalysisWorkspace({result,onExplain}:{result:DashboardRunSuccess;onExplain:()=>void}){
 const a=result.charts[0],b=result.charts[1],ranks=result.insight.items.filter((x):x is Extract<typeof x,{type:'rank'}>=>x.type==='rank'),changes=result.insight.items.filter((x):x is Extract<typeof x,{type:'period_change'}>=>x.type==='period_change');
 return <div className="workspace"><header className="instrument"><div className="identity"><i>{result.provenance.instrument.displayName.slice(0,1)}</i><div><small>{result.provenance.instrument.symbol} · {result.spec.instrument.assetType}</small><h2>{result.provenance.instrument.displayName}</h2></div></div><div className="intent"><small>ANALYSIS</small><p>{result.insight.intentSummary||result.input}</p></div><div className="range"><b>Last {result.provenance.timeRange.count} trading days</b><span>As of {date(result.provenance.asOf)}</span></div></header>
 {(changes.length>0||ranks.length>0)&&<div className="summaries">{changes.map(x=><section className="summary" key={x.metric}><header>{x.metricLabel}<small>PERIOD CHANGE</small></header><div className="kpis"><Kpi label="Start" value={val(x.startValue,x.unit)}/><Kpi label="End" value={val(x.endValue,x.unit)}/><Kpi label="Change" value={`${x.changePct>0?'+':''}${val(x.changePct,'%')}`} tone={x.changePct>=0?'positive':'negative'}/></div></section>)}{ranks.map(x=><section className="summary" key={x.transformId}><header>{x.order==='desc'?'Highest':'Lowest'} {x.metricLabel}<small>TOP {x.limit}</small></header><div className="rank-preview">{x.points.slice(0,3).map((p,i)=><span key={p.date}><b>{String(i+1).padStart(2,'0')}</b>{date(p.date)}<strong>{val(p.value,p.unit)}</strong></span>)}</div></section>)}</div>}
 <div className="chart-grid">{a&&<Chart chart={a} series={result.spec.views[0]?.series.map(s=>label(result,s.field))??[]} main/>}{b?<Chart chart={b} series={result.spec.views[1]?.series.map(s=>label(result,s.field))??[]}/>:<aside className="insight"><header>IN THIS VIEW <button onClick={onExplain}>Schema ↗</button></header><h3>{result.spec.views[0]?.title}</h3><div className="metric-list">{result.spec.views[0]?.series.map(s=><span key={s.id}><i className={s.mark}/>{label(result,s.field)}</span>)}</div>{ranks.map(x=><div className="rank-list" key={x.transformId}><b>{x.metricLabel}</b>{x.points.slice(0,4).map((p,i)=><span key={p.date}><i>{String(i+1).padStart(2,'0')}</i>{date(p.date)}<strong>{val(p.value,p.unit)}</strong></span>)}</div>)}{!ranks.length&&<p>{result.insight.intentSummary}</p>}</aside>}</div>
 <div className="provenance">◒ &nbsp;{result.spec.dataSource.resolved==='embedded_mock'?'Embedded mock data':result.spec.dataSource.resolved} &nbsp;·&nbsp; As of {date(result.provenance.asOf)} &nbsp;·&nbsp; {result.provenance.timeRange.count} trading days<button onClick={onExplain}>Data details ↗</button></div><div className="workspace-bottom"><span>✳ &nbsp;Explore the shape of this analysis</span><button onClick={onExplain}>View generated schema ↗</button></div></div>
}
function Chart({chart,series,main=false}:{chart:DashboardChartResult;series:string[];main?:boolean}){const el=useRef<HTMLDivElement>(null);useEffect(()=>{if(!el.current)return;const c=echarts.init(el.current);c.setOption(chart.option,true);const r=new ResizeObserver(()=>c.resize());r.observe(el.current);return()=>{r.disconnect();c.dispose()}},[chart]);return <section className={main?'chart main-chart':'chart'}><header><div><small>{main?'PRIMARY VIEW':'SUPPORTING VIEW'}</small><h3>{chart.title}</h3></div><button aria-label="Chart options">···</button></header><div className="legend">{series.map((s,i)=><span key={s}><i className={'swatch s'+i%4}/>{s}</span>)}</div><div ref={el} className="echart" role="img" aria-label={chart.title}/></section>}
function Kpi({label,value,tone}:{label:string;value:string;tone?:string}){return <div><small>{label}</small><b className={tone}>{value}</b></div>}
function label(r:DashboardRunSuccess,id:string){return r.spec.metrics.find(m=>m.id===id)?.label??id}
function date(s:string){return new Intl.DateTimeFormat('en',{month:'short',day:'numeric'}).format(new Date(s+'T00:00:00'))}
function val(n:number,u:string){if(u==='%')return new Intl.NumberFormat('en',{maximumFractionDigits:2}).format(n)+'%';if(u==='share'&&Math.abs(n)>=1_000_000)return new Intl.NumberFormat('en',{notation:'compact',maximumFractionDigits:2}).format(n);return new Intl.NumberFormat('en',{maximumFractionDigits:2}).format(n)}
